export const experiencia_professional = [
  {
    CAT: "Experiència Professional",
    ES: "Experiencia Profesional",
    EN: "Professional Experience",
    FR: "Expérience Professionnelle",
    RU: "Профессиональный опыт",
    DE: "Berufserfahrung",
    IT: "Esperienza Professionale",
    PT: "Experiência Profissional",
    NL: "Professionele ervaring",
    AR: "أون",
    ZH: "专业经验",
  },
];
export const feines = [
  {
    CAT: "Director Tècnic",
    ES: "Director Técnico",
    EN: "CTO",
    FR: "Directeur Technique",
    RU: "Технический директор",
    DE: "Technischer Direktor",
    IT: "Direttore Tecnico",
    PT: "Diretor Técnico",
    NL: "Technisch Directeur",
    AR: "مؤتمرات",
    ZH: "技术总监",
  },
  {
    CAT: "Cap de Projectes",
    ES: "Director de Proyectos",
    EN: "Project Manager",
    FR: "Chef de projets",
    RU: "Руководитель проекта",
    DE: "Projektmanager",
    IT: "Manager di Proyecto",
    PT: "Gestor de projeto",
    NL: "Projectleider",
    AR: "مدير فرع",
    ZH: "专案经理",
  },
  {
    CAT: "Responsable de Servei al Client",
    ES: "Responsable de Servicio al Cliente",
    EN: "Service Account Manager",
    FR: "Gestionnaire de Service de Comptes",
    RU: "Менеджер по обслуживанию учетной записи",
    DE: "Service Account Manager",
    IT: "Amministratore dei Servizio del Conteggi",
    PT: "Gerente de Serviço de Conta",
    NL: "Service Account Manager",
    AR: "مدير المشروع",
    ZH: "服务客户经理",
  },
  {
    CAT: "Mestre",
    ES: "Profesor",
    EN: "Teacher",
    FR: "Prof",
    RU: "Преподаватель",
    DE: "Lehrer",
    IT: "Professore",
    PT: "Professor",
    NL: "Docent",
    AR: "المدير الفني",
    ZH: "老师",
  },
  {
    CAT: "Responsable de Producte",
    ES: "Jefe de Producto",
    EN: "Product Manager",
    FR: "Responsable du produit",
    RU: "Менеджер по продукту",
    DE: "Produktmanager",
    IT: "Gestione del prodotto",
    PT: "Gerente de produto",
    NL: "Verantwoordelijk voor product",
    AR: "معلم",
    ZH: "负责产品",
  },
  {
    CAT: "Delegat Regional",
    ES: "Delegado Regional",
    EN: "Branch Manager",
    FR: "Délégué Régional",
    RU: "Менеджер филиала",
    DE: "Manager der Niederlassung",
    IT: "Delegato regionale",
    PT: "Gerente de Branch",
    NL: "Regionale afgevaardigde",
    AR: "مدير الإنتاج",
    ZH: "区域代表",
  },
  {
    CAT: "Supervisor d'Efectes Visuals",
    ES: "Supervisor de efectos visuales",
    EN: "Visual effects Supervisor",
    FR: "Superviseur des effets visuels",
    RU: "Руководитель визуальных эффектов",
    DE: "Supervisor für visuelle Effekte",
    IT: "Supervisore degli effetti visivi",
    PT: "Supervisor de efeitos visuais",
    NL: "Supervisor van visuele effecten",
    AR: "مدير حساب الخدمة",
    ZH: "视觉效果的主管",
  },
  {
    CAT: "Desenvolupador Web",
    ES: "Desarrollador Web",
    EN: "Web Developer",
    FR: "Développeur web",
    RU: "веб-разработчик",
    DE: "Web-Entwickler",
    IT: "Sviluppatore web",
    PT: "Desenvolvedor da Web",
    NL: "Webontwikkelaar",
    AR: "كل الحقوق محفوظة",
    ZH: "Web开发人员",
  },
  {
    CAT: "Periodista",
    ES: "Periodista",
    EN: "Journalist",
    FR: "Journaliste",
    RU: "Журналист",
    DE: "Journalist",
    IT: "Giornalista",
    PT: "Jornalista",
    NL: "Journalist",
    AR: "المشرف على المؤثرات المرئية",
    ZH: "记者",
  },
  {
    CAT: "Empresari",
    ES: "Empresario",
    EN: "Businessman",
    FR: "Entrepreneur",
    RU: "Бизнесмен",
    DE: "Geschäftsmann",
    IT: "Uomo d'affari",
    PT: "Homem de negocios",
    NL: "Zakenman",
    AR: "هوايات",
    ZH: "商人",
  },
];
export const entrevistes_i_conferencies = [
  {
    CAT: "Entrevistes i Conferències",
    ES: "Entrevistas y conferencias",
    EN: "Interviews and conferences",
    FR: "Entretiens et conférences",
    RU: "Интервью и конференции",
    DE: "Interviews und Konferenzen",
    IT: "Interviste e conferenze",
    PT: "Entrevistas e Conferências",
    NL: "Interviews en conferenties",
    AR: "اللغات",
    ZH: "访谈和会议",
  },
];
export const entrevistes = [
  {
    CAT: "Entrevistes",
    ES: "Entrevista",
    EN: "Interviews",
    FR: "Entretiens",
    RU: "Интервью",
    DE: "Interviews",
    IT: "Colloquio",
    PT: "Entrevistas",
    NL: "Sollicitatiegesprekken",
    AR: "المؤتمرات",
    ZH: "面试",
  },
];
export const conferencies = [
  {
    CAT: "Conferències",
    ES: "Conferencias",
    EN: "Conferences",
    FR: "Conférences",
    RU: "Конференции",
    DE: "Konferenzen",
    IT: "Conferenze",
    PT: "Conferências",
    NL: "Conferenties",
    AR: "المقابلات والمؤتمرات",
    ZH: "会议",
  },
];
