export const idiomes_web = [
  "CAT",
  "ES",
  "EN",
  "FR",
  "RU",
  "DE",
  "IT",
  "PT",
  "NL",
  "AR",
  "JA",
  "ZH",
];
export const idiomes = [
  {
    CAT: "Idiomes",
    ES: "Idiomas",
    EN: "Languages",
    FR: "Langues",
    RU: "Языки",
    DE: "Sprachen",
    IT: "Lingue",
    PT: "Línguas",
    NL: "Talen",
    AR: "الانتماءات",
    JA: "言語",
    ZH: "语言",
  },
];
export const llengues = [
  {
    CAT: "Català",
    ES: "Catalán",
    EN: "Catalan",
    FR: "Catalan",
    RU: "Каталон",
    DE: "Katalanisch",
    IT: "Catalano",
    PT: "Catalão",
    NL: "Catalaans",
    AR: "صحافي",
    JA: "カタロニャー",
    ZH: "加泰罗尼亚州",
  },
  {
    CAT: "Castellà",
    ES: "Español",
    EN: "Spanish",
    FR: "Espagnol",
    RU: "испанский",
    DE: "Spanisch",
    IT: "Spagnolo",
    PT: "Espanhol",
    NL: "Spaans",
    AR: "الكاتالونية",
    JA: "スペイン語",
    ZH: "西班牙语",
  },
  {
    CAT: "Anglès",
    ES: "Inglés",
    EN: "English",
    FR: "Anglais",
    RU: "английский",
    DE: "Englisch",
    IT: "Inglese",
    PT: "Inglês",
    NL: "Engels",
    AR: "الأسبانية",
    JA: "英語",
    ZH: "英语",
  },
  {
    CAT: "Francès",
    ES: "Francés",
    EN: "French",
    FR: "Français",
    RU: "Французский",
    DE: "Französisch",
    IT: "Francese",
    PT: "Francês",
    NL: "Frans",
    AR: "إنجليزي",
    JA: "フランス語",
    ZH: "法语",
  },
  {
    CAT: "Rus",
    ES: "Ruso",
    EN: "Russian",
    FR: "Russe",
    RU: "русский",
    DE: "Russisch",
    IT: "Ruso",
    PT: "Russo",
    NL: "Russisch",
    AR: "الفرنسية",
    JA: "ロシア",
    ZH: "俄语",
  },
  {
    CAT: "Alemany",
    ES: "Alemán",
    EN: "German",
    FR: "Allemand",
    RU: "Немецкий",
    DE: "Deutsch",
    IT: "Tedesco",
    PT: "Alemão",
    NL: "Duits",
    AR: "الروسية",
    JA: "ドイツ人",
    ZH: "德语",
  },
  {
    CAT: "Italià",
    ES: "Italiano",
    EN: "Italian",
    FR: "Italien",
    RU: "Итальянский",
    DE: "Italienisch",
    IT: "Italiano",
    PT: "Italiano",
    NL: "Italiaans",
    AR: "ألمانية",
    JA: "イタリアの",
    ZH: "意大利人",
  },
  {
    CAT: "Portuguès",
    ES: "Portugués",
    EN: "Portuguese",
    FR: "Portugais",
    RU: "португальский",
    DE: "Portugiesisch",
    IT: "Portoghese",
    PT: "Português",
    NL: "Portugees",
    AR: "الإيطالية",
    JA: "ポルトガル語",
    ZH: "葡萄牙语",
  },
  {
    CAT: "Xinès",
    ES: "Chino",
    EN: "Chinese",
    FR: "Chinois",
    RU: "китайский",
    DE: "Chinesisch",
    IT: "Chino",
    PT: "Chinês",
    NL: "Chinese",
    AR: "البرتغالية",
    JA: "中国語",
    ZH: "中国人",
  },
];
